### ISSUE TITLE
How to keep PostgresServer running

### ISSUE THREAD

**Issue by giselle197** [orm011/pgserver#3]
Thanks for this incredible work on helping me circumvent the sudo privilege and giving me a quick start to use the postgres db!

I transformed https://colab.research.google.com/github/orm011/pgserver/blob/master/pgserver-example.ipynb into a Python script (pgserver_example.py) and executing it.

Although I've set the cleanup_mode:
```python
import pgserver
srv = pgserver.get_server('./mypgdata', cleanup_mode=None)

from sqlalchemy_utils import create_database, database_exists
from sqlalchemy import create_engine

dburi = srv.get_uri(database='mydb')
print(dburi)
if not database_exists(dburi):
    create_database(dburi)
engine = create_engine(dburi)
```
The service stops after this script finished. I'm wondering how I can keep the PostgresServer running, similar to how fastapi occupies a terminal.

Thanks again for your help!

**Comment by orm011** [comment]
Oops, only saw this issue just now. 
Could you let me know where you are running it and what command made you realize it wasn't running?

**Comment by giselle197** [comment]
Ah, I check with `ps` and it is indeed running.
The process is like `.../site-packages/pgserver/pginstall/bin/postgres -D {database_path} -h  -k {database_path}`

No further questions. Thanks for your reply!
